Repository PositiveYou/NetHood, pull requests merged in 2018-10, with the labels that each got.

#44 Security issue - Django dependency version update
  requirements.txt
Labels: enhancement

#45 Use Redux to handle User state
  nethood-react/package-lock.json
  nethood-react/package.json
  nethood-react/src/App.js
  nethood-react/src/index.js
  nethood-react/src/reducers/user.js
Labels: enhancement

#46 Add layout components to the main page.
  nethood-react/src/App.js
  nethood-react/src/comps/Navigation.js
  nethood-react/src/comps/Site.js
  nethood-react/src/comps/ToolBar.js
Labels: enhancement

#55 Delete the secretly secretes!
  nethood/nethood/secret_settings.py
Labels: bug

#58 Add Bootstrap as a dependency
  nethood-react/package-lock.json
  nethood-react/package.json
Labels: Front-End, enhancement

#66 chor: Update dependencies
  nethood-react/package-lock.json
Labels: Front-End, enhancement

#72 Make the basic API work without errors
  .gitignore
  nethood/api/models.py
  nethood/api/views.py
Labels: Back-End, enhancement

#74 Add social Auth to Django
  nethood/api/models.py
  nethood/nethood/secret_settings.py.tamplate
  nethood/nethood/settings.py
  nethood/nethood/urls.py
  requirements.txt
Labels: Back-End, enhancement
